### PR TITLE
ci: fix github action

### PR DESCRIPTION
**Pull request by yi-Xu-0100**
### Description

update GitHub action to build packages for different platforms.

See test in : https://github.com/yi-Xu-0100/electron-vite-vue/actions/runs/2736227031

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Other

### CODE REVIEW

**Review by caoxiemeihao — APPROVED** [review]
This is an amazing PR. 🎉

**Comment by caoxiemeihao** [comment]
Maybe, we also need some other actions for PR.  😄

e.g.

- `package-lock.json`, `yarn.lock`, `pnpm-lock.yaml` are not allowed.
- Run lint tools check PR code.

**Comment by yi-Xu-0100** [comment]
@caoxiemeihao why not add it into .gitignore?

for lint, I think it should have a common config for this repo, and could lint in local.

**Comment by caoxiemeihao** [comment]
[Include package-lock.json #192](https://github.com/electron-vite/electron-vite-vue/issues/192)
This consideration is consistent with the template created by `create-vite`
This project is essentially to complement electron-template not provided by `create-vite`

**Comment by yi-Xu-0100** [comment]
@caoxiemeihao ok, I got it. The check ignore action and the lint action can be combined into one job, because they all used to check PR. Which tools will be used to check the lint? Like lint CI in [vite](https://github.com/vitejs/vite/blob/main/.github/workflows/ci.yml)?

https://github.com/vitejs/vite/blob/183c6fb62fc6f1f2a2d3e883a76aa60b3ed21ba0/.github/workflows/ci.yml#L95-L126

And we may need a [CONTRIBUTING.md](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md) like vite to show the correct PR workflow.

By the way, I find the merge option is always using the default setting, maybe we should use `squash and merge` for keeping the log clear. The different among the default setting, `rebase and merge` and `squash and merge` is difficult to explain in simple terms, so it is better to search the relevant explanatory articles.

**Comment by caoxiemeihao** [comment]
Looks like a great idea, you can do it your way. *(大哥，这块你看着办，不侵入模板就行 😂)*

**Pull request merged**
